# Project: Projeto1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Dom_HJRV_Controller.o Dom_HJRV_Model.o Dom_HJRV_PROJETO.o Dom_HJRV_View.o
LINKOBJ  = Dom_HJRV_Controller.o Dom_HJRV_Model.o Dom_HJRV_PROJETO.o Dom_HJRV_View.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Projeto1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Dom_HJRV_Controller.o: Dom_HJRV_Controller.c
	$(CPP) -c Dom_HJRV_Controller.c -o Dom_HJRV_Controller.o $(CXXFLAGS)

Dom_HJRV_Model.o: Dom_HJRV_Model.c
	$(CPP) -c Dom_HJRV_Model.c -o Dom_HJRV_Model.o $(CXXFLAGS)

Dom_HJRV_PROJETO.o: Dom_HJRV_PROJETO.c
	$(CPP) -c Dom_HJRV_PROJETO.c -o Dom_HJRV_PROJETO.o $(CXXFLAGS)

Dom_HJRV_View.o: Dom_HJRV_View.c
	$(CPP) -c Dom_HJRV_View.c -o Dom_HJRV_View.o $(CXXFLAGS)
